Edit farsi translation and add 'words'
adityatelange/hugo-PaperMod pull request #1290
Opened 2023-08-15 21:18 UTC by hialisabet

I suggest more comfortable translation for 'prev_page' and 'next_page'. Also, I added farsi translation for missing 'words'.

**What does this PR change? What problem does it solve?**

There are more comfortable farsi translations for 'prev_page' and 'next_page'. also the translation of 'words' was missing in farsi. because of different directions, It ruins the style of the text!

**Was the change discussed in an issue or in the Discussions before?**

No, I just noticed and decided to solve it.

## PR Checklist

- [x] This change adds/updates translations and I have used the [template present here](https://github.com/adityatelange/hugo-PaperMod/wiki/Translations#want-to-add-your-language-).
- [ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have verified that the code works as described/as intended.
- [ ] This change adds a Social Icon which has a permissive license to use it.
- [ ] This change **does not** include any CDN resources/links.
- [ ] This change **does not** include any unrelated scripts such as bash and python scripts.
- [ ] This change updates the overridden internal templates from HUGO's repository.

2023-08-19 07:28 UTC, adityatelange reviewed
Hi @pikhosh @mehdy, can you please help reviewing? Thanks.

2023-08-19 08:26 UTC, mehdy requested changes

2023-08-19 08:26 UTC, mehdy commented on i18n/fa.yaml
> +    one : "1 دقیقه"
Why would you want to change this? I think it's better to keep using the Persian numbers.

2023-08-19 08:26 UTC, mehdy commented on i18n/fa.yaml
> +    one : "کلمه"
Shouldn't this be "۱ کلمه" or "یک کلمه"?

2023-08-19 08:26 UTC, mehdy commented on i18n/fa.yaml
> +  translation: "ترجمه‌ها"
I think the correct form would be using half-space. Ref: https://utype.ir/blog/%D9%86%DB%8C%D9%85-%D9%81%D8%A7%D8%B5%D9%84%D9%87-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C/#:~:text=%DB%B5%2D%20%D8%AF%D8%B1%20%D8%B2%D9%85%D8%A7%D9%86,%DA%A9%D8%AA%D8%A7%D8%A8%E2%80%8C%D9%87%D8%A7%D8%8C%20%D8%AE%D8%A7%D9%86%D9%87%E2%80%8C%D9%87%D8%A7

2023-08-19 08:26 UTC, mehdy commented on i18n/fa.yaml
> +    one : "کلمه"
If you like, you could use "واژه" as well.

2023-09-12 09:17 UTC, mehdy commented on i18n/fa.yaml
> +    one : "1 دقیقه"
@hialisabet Okay, I didn't notice it. But then I think it'd make sense to change the plural forms to show the Persian numbers.

2023-09-12 09:18 UTC, mehdy commented on i18n/fa.yaml
> +  translation: "ترجمه‌ها"
I don't know if you've changed the code or if I was confused before. Anyway, you're doing the right thing now.

2024-10-04 21:36 UTC, closed without merging